[IN-224] feat: props extension
Mechanics-cloud/OurProject pull request #125
Opened 2024-12-17 18:03 UTC by KvashninAlexander2023

- [x] расширил пропсы (из вне можно управлять базовым функционалом swiper)  
- [x] добавил возможность редактировать классы

2024-12-24 09:27 UTC, dariametelitsa commented
![image](https://github.com/user-attachments/assets/8d832660-5bab-426e-b255-c657b35195f7)
Изменения в добавлении поста перекрыли функциональные кнопки (упоминала об этой задаче на созвоне)

2024-12-24 09:29 UTC, dariametelitsa commented
![image](https://github.com/user-attachments/assets/699c768b-125e-4093-a5a4-57eb069dc0d3)
На миниатюрах согласна, точки много занимают от контента. В Home пока не смогла проверить, нужны друзья с каруселью

2024-12-24 18:33 UTC, KvashninAlexander2023 commented
> ![image](https://private-user-images.githubusercontent.com/109726679/398378620-8d832660-5bab-426e-b255-c657b35195f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNjU0NDcsIm5iZiI6MTczNTA2NTE0NywicGF0aCI6Ii8xMDk3MjY2NzkvMzk4Mzc4NjIwLThkODMyNjYwLTViYWItNDI2ZS1iMjU1LWM2NTdiMzUxOTVmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxODMyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmU5NGEwNzMyNDc5NTYxZGZmZWE3ZTU4NWE1N2I2YmVmODY3ZDk4YTk1YzU2MThjMzY3YWNjNWU4NDM4ODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.btBDYjHH4IvnUTd1mFmeu9m2dDJ_K2twgsKTS60xXBE) Изменения в добавлении поста перекрыли функциональные кнопки (упоминала об этой задаче на созвоне)

поправил

2024-12-24 18:36 UTC, KvashninAlexander2023 commented
> ### Choose a reason for hiding this comment
> The reason will be displayed to describe this comment to others

уменьшил

2024-12-25 17:28 UTC, KvashninAlexander2023 commented
Нет возможности добавить SB, т.к. не работает

2024-12-26 09:59 UTC, dariametelitsa reviewed
По стилям выглядит ок, немного смущает только обилие `!important`
По sb - надо чинить

2024-12-26 09:59 UTC, dariametelitsa commented on src/common/components/swiper/CustomSwiper.tsx
> +} & Omit<SwiperProps, 'className' | 'images'>
А зачем ты определяешь className? Может убрать из типа и из Omit?

2024-12-26 09:59 UTC, dariametelitsa commented on src/common/components/swiper/CustomSwiper.tsx
> +    return (
Интересное решение👍

2024-12-30 14:59 UTC, dariametelitsa approved these changes

2024-12-30 14:59 UTC, dariametelitsa commented on .storybook/preview.ts
>  import '@fontsource/inter/400.css'
А зачем из СБ глобальные стили убрал?

2024-12-30 14:59 UTC, dariametelitsa commented on src/styles/customStylesForSwiper.css
Стили для свайпера лучше возле свайпера и положить (в компоненте)

2025-01-02 07:31 UTC, jocker-py requested changes

2025-01-02 07:31 UTC, jocker-py commented on src/common/components/swiper/CustomSwiper.tsx
> +    return (
Swiper может использоваться не только для фоток постов, очень становиться зависимым комонент от конкретной сущности. Может будет сделать компонент Stub(Заглушка), который будет принимать alt, text, src и тогда использовать уже не в CustomSwiper, а снаружи типа images.length === 0 ? Stub alt={t.profilePage.noPosts.alt} text={t.basic.errors.emptyImages} src={noPostImage}. Этот Stub мы тогда сможем переиспользовать в других местах

2025-01-02 07:31 UTC, jocker-py commented on src/common/components/swiper/CustomSwiper.tsx
> +    return (
и вот с этой проверкой не понятно зачем тогда код выше:

   {item.images.length > 0 ? (
          <CustomSwiper images={item.images} />
        ) : (
          t.basic.errors.emptySlider
          t.basic.errors.emptySwiper
        )}

2025-01-02 07:31 UTC, jocker-py commented on src/styles/customStylesForSwiper.css
согласен

2025-01-02 07:31 UTC, jocker-py commented on src/styles/customStylesForSwiper.css
> +.addPost .swiper-pagination {
класс addPost не должен лежать здесь, он же супер специфичный, должен лежать рядом с добавлением постов

2025-01-19 06:45 UTC, merged