IN-13 / add ReCAPTCHA
Mechanics-cloud/OurProject pull request #35
Opened 2024-09-18 15:19 UTC by OchirovBair

2024-09-18 15:46 UTC, dariametelitsa requested changes
Добавить index в папку.
Проверить в SB отображение (у меня элемент не отображается)

2024-09-19 01:26 UTC, OchirovBair commented
по индексу принял
по  SB какую ошибку выдает или вообще ничего не отображает без ошибок?

2024-09-19 10:02 UTC, OchirovBair commented
> Добавить index в папку. Проверить в SB отображение (у меня элемент не отображается)

Добавил
Поправил отображение

2024-09-19 10:40 UTC, dariametelitsa reviewed
Поправь импорт на 
"import { ReCAPTCHA, ReCAPTCHAProps } from 'react-google-recaptcha'"
чтобы линтер не выкидывал warning.

2024-09-19 14:02 UTC, dariametelitsa approved these changes

2024-09-19 14:03 UTC, dariametelitsa commented
Ок, такой вариант с игнором в данном случае самое то, чтобы этот warning через весь проект не тащить

2024-09-19 14:04 UTC, merged