In 155 / oAuth 2.0 with Google and Github
Mechanics-cloud/OurProject pull request #66
Opened 2024-10-04 12:56 UTC by tanya-kostecki

- [ ] add authorization with Github
- [ ] add authorization with Google

2024-10-09 11:33 UTC, dariametelitsa reviewed
Кратко:
- в me() не должен передаваться токен
- кое где пути заменить на переменную
- проект работает корректно? У меня страницы с регситрацией через внешний сервисы крашатся

2024-10-09 11:33 UTC, dariametelitsa commented on src/common/components/pagination/Pagination.stories.tsx
> +    email: 'kminall0@oauth-callback-google.com',
Тут видимо автозаменой случайно зацепило. Это тестовые данные, не страшно. Но в целом с автозаменой аккуратнее)

2024-10-09 11:33 UTC, dariametelitsa commented on src/features/auth/api/auth.api.ts
> +  public async me(accessToken: string): Promise<Profile> {
Зачем в me явно цеплять хедер (токен), если axios это делает в каждом запросе?

2024-10-09 11:33 UTC, dariametelitsa commented on src/features/auth/model/authStore.ts
> +      await this.me(accessToken)
это не нужно добавлять

2024-10-09 11:33 UTC, dariametelitsa commented on src/features/auth/model/authStore.ts
> +      return res.data.accessToken
Тебе сюда нужно по аналогии с логином стандартным в конце запроса 
`await this.me()` прицепить и токен отправится

2024-10-09 11:33 UTC, dariametelitsa commented on src/features/auth/model/authStore.ts
> +  async me(accessToken: string) {
Аналогично

2024-10-09 11:33 UTC, dariametelitsa commented on src/features/auth/ui/signUp/GoogleLoginButton.tsx
> +import { authApi } from '@/features/auth'
Лишний импорт

2024-10-09 11:33 UTC, dariametelitsa commented on src/features/auth/ui/signUp/GoogleLoginButton.tsx
> +
Здесь возможно нужно токен в local store положить (если ранее нигде не сетался), после чего выполнить me()

2024-10-09 11:33 UTC, dariametelitsa commented on src/pages/github/index.tsx
> +        authStore.me(accessToken as string).then(() => router.push('/profile'))
Путь лучше из переменной использовать

2024-10-09 11:33 UTC, dariametelitsa commented on src/pages/github/index.tsx
> +        console.warn('No token')
В консоли не должны выводиться ошибки. Тут надо подумать как обработать ситуацию. Если верно понимаю, вероятность сюбда попасть близится к 0?

2024-10-09 11:33 UTC, dariametelitsa commented on src/features/auth/ui/signUp/GoogleLoginButton.tsx
> +            await router.push('/profile')
Путь лучше из переменной использовать

2024-10-09 12:14 UTC, jocker-py commented on src/pages/github/index.tsx
> +        console.warn('No token')
обычно просто пробрасывают ошибку дальше используй throw Error
также можно показать toast message

2024-10-10 10:06 UTC, dariametelitsa requested changes

2024-10-10 10:06 UTC, dariametelitsa commented on src/features/auth/ui/ExternalServicesRegistration.tsx
> +          onClick={() => googleLogin()}
`onClick={googleLogin}` можно сократить запись, как ниже

2024-10-10 10:06 UTC, dariametelitsa commented on src/pages/github/index.tsx
> +        console.warn('No token')
Да, тут тоже можно `throw Error`

2024-10-10 10:17 UTC, tanya-kostecki commented on src/common/utils/setAccessToken.ts
> +export const setAccessToken = (accessToken?: string) => {
сделала как до этого было предложено

2024-10-10 10:18 UTC, tanya-kostecki commented on src/features/auth/model/authStore.ts
> +      setAccessToken(res.data.accessToken)
я пока подправила только в своем коде, если нужно могу везде подправить

2024-10-10 10:20 UTC, tanya-kostecki commented on src/common/utils/responseErrorHandler.ts
> -  if (!isAxiosError(error) || !error.response?.data?.messages) {
здесь исправления уже не особо актуальны, могу вернуть прежнюю версию кода

2024-10-10 10:23 UTC, tanya-kostecki commented on src/features/auth/ui/ExternalServicesRegistration.tsx
> +          onClick={() => googleLogin()}
изначально у меня на нее компилятор ругался, поэтому оставила

2024-10-10 10:59 UTC, dariametelitsa commented on src/features/auth/model/authStore.ts
> +      setAccessToken(res.data.accessToken)
Или так или новую задачу с описанием. Тут отталкивайся от трудозатрат. Просто если не будем подправлять/отмечать необходимость разрозненный код будет накапливаться

2024-10-10 11:02 UTC, dariametelitsa commented on src/common/utils/setAccessToken.ts
> +export const setAccessToken = (accessToken?: string) => {
> сделала как до этого было предложено

Это ок. Мы постепенно улучшаем код) 
В данном контексте просто неочевидно использовать `setAccessToken()` для удаления, нейминг противоречит непосредственному функционалу

2024-10-10 13:56 UTC, dariametelitsa commented on src/common/utils/responseErrorHandler.ts
> -  if (!isAxiosError(error) || !error.response?.data?.messages) {
Тут можно попробовать порядок if-ов изменить и подходящий тебе (проверка на строку) поставить выше с return

2024-10-11 14:41 UTC, dariametelitsa approved these changes

2024-10-14 13:00 UTC, jocker-py approved these changes

2024-10-14 14:19 UTC, merged