IN-103 / feat: add profile photo modal
Mechanics-cloud/OurProject pull request #81
Opened 2024-10-15 10:26 UTC by OchirovBair

- [ ] добавлено модальное окно для выбора аватара профиля

2024-10-20 08:29 UTC, jocker-py requested changes

2024-10-21 09:30 UTC, OchirovBair commented on src/features/profile/settings/avatarDialog/model/avatarDialog/useAvatarDialog.ts
> +                error: 'Blob error',
Это скорее ошибка для компонента который будет ловить этот объект, но для пользователя добавлю в этом кейсе setError("Unknown error")

2024-10-21 10:16 UTC, dariametelitsa commented on src/features/profile/settings/avatarDialog/ui/AvatarDialog.tsx
> +          className={`flex items-center ${
Не обязательно, но здесь можно cn() использовать

2024-10-21 10:16 UTC, dariametelitsa commented on src/features/profile/settings/avatarDialog/ui/chooseFileButton/ChooseFileButton.tsx
> +export const ChooseFileButton = ({
Вынес в model схему, можно тогда и логику вынесли туда

2024-10-21 10:16 UTC, dariametelitsa commented on src/features/profile/settings/avatarDialog/ui/chooseFileButton/ChooseFileButton.tsx
> +        debugger
Нельзя пушить debugger в дев

2024-10-21 10:16 UTC, dariametelitsa commented on src/common/color-palette/ColorPalette.mdx
> +[//]: # "import {  } from '@storybook/addon-docs'"
Это то, а что у тебя ругается?

2024-10-21 10:16 UTC, dariametelitsa commented on src/features/profile/settings/avatarDialog/model/avatarDialog/useAvatarDialog.ts
> +                error: 'blob error',
Если ошибка улетит на ui нужен перевод

2024-10-21 11:44 UTC, OchirovBair commented on src/common/enums/enums.ts
> +  OneMB = 1024 * 1024,
export enum UserAvatarSizes {
  OneMB = 1024 * 1024,
}

Так?

2024-10-21 11:49 UTC, OchirovBair commented on src/pages/profile/settings/index.tsx
> +export default withProtection(ProfileSettings, true)
эта страница от Тани будет, я так для себя накидал, ей нужно будет подтянуть мои изменения потом из dev, когда залью и заменить полностью страницу settings

2024-10-21 11:51 UTC, OchirovBair commented on src/features/profile/settings/avatarDialog/model/types.ts
> +export type ModalPhotoSaveHandler = (item: PhotoResult) => void
данная типизация функции два раза используется, первый - в типе ниже, воторой - в хуке useAvatarDialog, если не делать все равно нужен будет тип PhotoResult в хуке useAvatarDialog

2024-10-21 11:57 UTC, OchirovBair commented on src/common/color-palette/ColorPalette.mdx
> +[//]: # "import {  } from '@storybook/addon-docs'"
переодически ошибка иморта, хотя пакета такого вообще нет @storybook/addon-docs

2024-10-21 11:58 UTC, OchirovBair commented on src/features/profile/settings/avatarDialog/model/avatarDialog/useAvatarDialog.ts
> +                error: 'blob error',
Это скорее ошибка для компонента который будет ловить этот объект, но для пользователя добавлен в этом кейсе setError("Unknown error")

2024-10-21 12:04 UTC, OchirovBair commented on src/features/profile/settings/avatarDialog/ui/chooseFileButton/ChooseFileButton.tsx
> +export const ChooseFileButton = ({
О какой логике речь? и куда в схему выносить?

2024-10-21 12:09 UTC, OchirovBair commented on src/features/profile/settings/avatarDialog/model/avatarDialog/useAvatarDialog.ts
> +                error: 'blob error',
подумал, и вообще убрал поле error, но setError("Unknown error") добавлю в Toast

2024-10-21 12:16 UTC, dariametelitsa commented on src/common/enums/enums.ts
> +  OneMB = 1024 * 1024,
export enum FileSizes { UserAvatar = 1024 * 1024, } - скорее так

2024-10-21 12:17 UTC, dariametelitsa commented on src/pages/profile/settings/index.tsx
> +export default withProtection(ProfileSettings, true)
Ок, просто такие мелочи можно потом не заметить / забыть исправить

2024-10-21 12:20 UTC, dariametelitsa commented on src/features/profile/settings/avatarDialog/ui/chooseFileButton/ChooseFileButton.tsx
> +export const ChooseFileButton = ({
разметку оставить здесь, а логику в хук и в папку model/chooseFileButton. Она уже создана, у тебя туда вынесена схема

2024-10-21 13:09 UTC, jocker-py requested changes

2024-10-21 13:09 UTC, jocker-py commented on src/features/profile/settings/avatarDialog/ui/chooseFileButton/ChooseFileButton.tsx
> +        debugger
debugger явно нужно убрать

2024-10-21 13:53 UTC, jocker-py commented on src/features/profile/settings/avatarDialog/ui/chooseFileButton/ChooseFileButton.tsx
> +  const { onPhotoChoose, t } = useChooseFile({ onErrorChange, onPhotoChange })
вот как-будто бы возвращать t из хука лишнее

2024-10-21 14:33 UTC, OchirovBair commented on src/features/profile/settings/avatarDialog/ui/chooseFileButton/ChooseFileButton.tsx
> +  const { onPhotoChoose, t } = useChooseFile({ onErrorChange, onPhotoChange })
в кнопке есть текст <span>{t.avatarModal.chooseButton}</span>

2024-10-22 04:54 UTC, merged