IN-111 / General Information page
Mechanics-cloud/OurProject pull request #82
Opened 2024-10-15 17:35 UTC by tanya-kostecki

- [x] created Settings page with Tabs
- [x] layout for General Information
- [x] form fields with react hook form
- [x] validation for form fields for General Information with zod
- [x] updateProfile api request
- [x] getProfile api request
- [x] update avatar request on form submission
- [x] add localization
- [x] display user info on profile page
- [x] userId in the profile url

2024-10-23 12:41 UTC, OchirovBair commented
![image](https://github.com/user-attachments/assets/e617c265-b644-4f48-a421-d96376f0a64c)
у дня рождения странная дата

2024-10-23 13:50 UTC, OchirovBair commented on src/features/profile/settings/generalInfo/model/useFillGeneralForm.ts
> +      // },
коммент

2024-10-23 13:50 UTC, OchirovBair commented on src/features/profile/settings/generalInfo/ui/AddPhoto.tsx
> +    }
это может вынести в useFillGeneralForm и компонент AddPhoto просто отрисовать в GeneralInfoForm не через форму (без FormAddPhoto)

2024-10-23 13:50 UTC, OchirovBair commented on src/features/profile/settings/generalInfo/model/generalInfoSchema.ts
> +
это можно будет убрать если выносить стейт и обработчки AddPhoto в хук useFillGeneralForm

2024-10-23 13:50 UTC, OchirovBair commented on src/features/profile/settings/generalInfo/model/profileStore.ts
> +        }
это убрать если из формы выносить фотку и сделать запрос на обновление в onSubmit в хуке useFillGeneralForm с проверкой перед отправкой currentPhoto !== photoObj.photo

2024-10-23 15:09 UTC, dariametelitsa reviewed
Большая работа проделана, круто!

2024-10-23 15:09 UTC, dariametelitsa commented on src/features/profile/settings/generalInfo/ui/index.tsx
> +        <ToastContainer />
Компонент в layout есть, по идее сюда добавлять не нужно.

2024-10-23 15:09 UTC, dariametelitsa commented on src/pages/github/index.tsx
> +          .then((res) => router.push(`${Paths.profile}/${res.userId}`))
Надо посмотреть где и в каких состояниях перехода нужно добавить id в путь. Сейчас локально id в пути не отображается

2024-10-23 15:09 UTC, dariametelitsa commented on src/pages/profile/[[...id]].tsx
> +  const avatar = userProfile?.avatars[0].url
Добавить `?`

2024-10-23 15:09 UTC, dariametelitsa commented on next.config.mjs
> +    domains: ['staging-it-incubator.s3.eu-central-1.amazonaws.com'],
А это где-то от инкубатора информация о domain есть?

2024-10-24 02:33 UTC, OchirovBair commented on src/features/profile/settings/generalInfo/model/useHandleCalendar.ts
> +  const calendarOutsideClickHandler = (e: MouseEvent) => {
Она не стала менять. Так как тачка будет отдельная

2024-10-24 08:37 UTC, tanya-kostecki commented on src/common/layout/layoutWithSidebar/LayoutWithSidebar.tsx
> +  const [loading, setLoading] = useState<boolean>(true)
C глобальным не работает, показывает состояние вечной загрузки, точно такая же логика на данный момент у нас реализована внутри useMe(), которая используется в _app.tsx. Поэтому решила сделать по аналогии и ничего не мудрить, чтобы не поломать приложение в других местах. А в целом, да, нужно поменять на глобальный

2024-10-24 08:44 UTC, dariametelitsa commented on src/features/profile/settings/generalInfo/model/useHandleCalendar.ts
> +  const calendarOutsideClickHandler = (e: MouseEvent) => {
Это да, но там и новые handler есть. Я не все помечала. + если какой-то код и так приходится дорабатывать (вносить изменения в файл) в целом хорошая практика и такие мелочи поправить.

2024-10-24 08:46 UTC, dariametelitsa commented on next.config.mjs
> +    domains: ['staging-it-incubator.s3.eu-central-1.amazonaws.com'],
Это я поняла. Вопрос скорее откуда ссылка появилась? Из ТЗ? Я решительно проморгала

2024-10-24 11:08 UTC, tanya-kostecki commented on next.config.mjs
> +    domains: ['staging-it-incubator.s3.eu-central-1.amazonaws.com'],
в консоли, когда ошибка упала. Я так о ней узнала

2024-10-24 12:37 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/model/useHandleCalendar.ts
> +  const calendarOutsideClickHandler = (e: MouseEvent) => {
я подправила нейминг, но только в своих файлах

2024-10-25 15:26 UTC, jocker-py requested changes

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/model/useCalendar.ts
> +
код с 18 по 38 строки. 
посмотри хук useClickOutside, ты его по факту сделала.
можно сделать разные реализации, мне больше нравится, где возвращается ref, а не передается в итоге будет выглядеть так и самое главное мы сможем это переиспользовать: 
// callback - который передаем в хук
const onClose = useCallback(() => setIsCalendarOpen(false), []);
const calendarRef = useClickOutside(callback);

// этот useEffect будет в хуке useClickOutside, чуть-что звони-пиши, мы с тобой сделаем красоту
useEffect(() => {
document.addEventListener('mousedown', callback)
return () => {
document.removeEventListener('mousedown', callback)
}
}, [])

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/model/useFetchLocations.ts
> +  const [cities, setCities] = useState<string[] | undefined>([])
null всегда предпочтительнее undefined, потому что undefined - программный, а null - всегда только от разрабов

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/model/useFillGeneralInfo.ts
> +  const { t } = useTranslation()
переводый, первой строкой в компоненте, это негласное правило

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/model/useFillGeneralInfo.ts
> +      if (currentPhoto !== photoObj.photo) {
хм, а почему не использовать свойство photoChanged

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/model/useFillGeneralInfo.ts
> +  const { t } = useTranslation()
const { t } = useTranslation()
по-моему ты его вообще здесь не используешь, может использовать его сразу в компоненте?

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/model/useFillGeneralInfo.ts
> +    useCalendar(setValue, 'dateOfBirth')
оставь только те хуки что используются в этом, остальные юзай из компонента, они у тебя очень аккуратные и будут там отлично смортеться, но это еще под вопросом, обсуждаемо))

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
> +      onSubmit,
onSubmit и handleSubmit в одном хуке взрывают мозг)

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/model/useFillGeneralInfo.ts
> +    onSubmit,
вот можно здесь : onSubmit: handleSubmit(onSubmit)

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
> +import CalendarOutline from '@/assets/icons/outlineIcons/CalendarOutline'
было бы супер что-то сделать с импортом, чтобы в итоге смотрелось или @/assets/icons или @/assets/icons/outlineIcons

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
> +                  <div ref={calendarRef}>
я бы порекомендовал элемент с ref вынести за условный рендеринг, порой может быть непредсказуемое поведение, тоесть: 

div ref={ref}>{isCalndarOpen && Component}<div

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
> +            <div className={'flex flex-col'}>
попробуй календарик вынести в отдельный компонент, много занимает и переиспользовать мы его точно потом смогли бы

2024-10-25 15:26 UTC, jocker-py commented on src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
> +              <div className={'flex gap-6'}>
селекты единственные кто работают со странами и городами, в отделную компоненту и там уже юзай хук
со странами и городами

2024-10-25 15:26 UTC, jocker-py commented on src/pages/profile/[[...id]].tsx
> +  const { t } = useTranslation()
const { t } = useTranslation() - самый первый в компоненте! будет правилом)

2024-10-25 15:26 UTC, jocker-py commented on src/pages/profile/settings/index.tsx
> +  const tabsData: TabsType[] = [
не изменные данные должны лежать вне компонента

2024-10-29 09:39 UTC, tanya-kostecki commented on src/pages/profile/settings/index.tsx
> +  const tabsData: TabsType[] = [
Отрисовка этих данных зависит от хука useTranslation(), поэтому эти данные все-таки изменяемые, я же не могу использовать хук вне компонента. Но можно, конечно, пойти на ухищрения и создать оберточную функцию и вызвать ее в компоненте с нужным аргументом. Будет такой вариант более правильным?

2024-10-29 10:09 UTC, tanya-kostecki commented on src/common/components/textfield/TextField.tsx
> +          {children && children}
думаю этот вопрос не ко мне, но могу глянуть потом

2024-10-30 14:29 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/model/profileStore.ts
> +          toast.success('Your settings are saved!')
в отдельную таску.

2024-10-30 14:29 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/model/profileStore.ts
> +        responseErrorHandler('error occurred')
в отдельную таску.

2024-10-30 16:13 UTC, tanya-kostecki commented on src/pages/profile/[[...id]].tsx
> +                  {' '}
это вебшторм так шалит при автосохранении

2024-10-30 16:15 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/model/useCalendar.ts
> +
ты просто по коммитам смотришь? этот код уже не актуальный, я это сама заметила и исправила позже на вот это 
const onClose = useCallback(() => {
    setIsCalendarOpen(false)
  }, [])

  const calendarRef = useClickOutside(onClose) 
должно быть где-то дальше по коммитам

2024-10-30 16:17 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/ui/FormCalendar.tsx
> +          className={
не совсем поняла где это?

2024-10-30 16:36 UTC, tanya-kostecki commented on src/common/hooks/useClickOutside.ts
> +  const ref = useRef<HTMLDivElement>(null)
может я тебя не совсем правильно поняла, ты вроде выше писал про хук который возвращает ref
Но не беда, исправлю

2024-10-31 06:31 UTC, jocker-py commented on src/features/profile/settings/generalInfo/ui/FormCalendar.tsx
> +          className={
здесь у тебя идет стилизация непосредственно иконки

2024-10-31 06:31 UTC, jocker-py commented on src/features/profile/settings/generalInfo/ui/AddPhoto.tsx
> +        <div
а здесь стилизация обертки

2024-10-31 09:54 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/ui/AddPhoto.tsx
> +        <div
эту компоненту делал Баир, я ее потом использую, Могу предположить, что из-за этого разные подходы к стилизации

2024-10-31 15:41 UTC, jocker-py approved these changes

2024-10-31 17:33 UTC, KvashninAlexander2023 approved these changes

2024-10-31 19:46 UTC, dariametelitsa commented on src/features/profile/settings/generalInfo/model/profileStore.ts
> +      if (res.status === 204) {
статус код в enum можно вынести

2024-11-01 08:53 UTC, dariametelitsa commented on src/common/layout/layoutWithSidebar/LayoutWithSidebar.tsx
> +  if (loading) {
В следующем ПР появился компонент для переключения загрузки, надо будет потом тут его использовать

2024-11-01 08:54 UTC, dariametelitsa commented on src/features/auth/model/index.ts
> +export { default as AuthStore } from './authStore'
по проекту инстансы стора  мы везде используем с маленькой буквы.

2024-11-01 08:55 UTC, dariametelitsa commented on src/features/profile/settings/generalInfo/api/profile.api.ts
> +  public uploadAvatar(file: File): Promise<any> {
Здесь any на axios response не получится заменить?

2024-11-01 08:57 UTC, dariametelitsa commented on src/features/profile/settings/generalInfo/api/profile.api.ts
> +    formData.append('file', file, file.name || 'avatar.jpg')
На сервер грузим png вроде, чтобы прозрачность у круга сохранить. В таком случае дефолтное расширение, наверное, тоже следует поправить

2024-11-01 09:01 UTC, dariametelitsa commented on src/features/profile/settings/generalInfo/ui/AddPhoto.tsx
> +export const AddPhoto = React.forwardRef<HTMLDivElement, Props>(
если ref не пробрасывать, то и обертка лишняя

2024-11-01 09:03 UTC, dariametelitsa commented on src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
> +              disabled={!isValid || isSubmitting || (!isDirty && !dirty)}
dirty's относятся к форме и фото, верно? Может их следует как-то уточнить, 2 похожих поля вводят в недоумение без контекста

2024-11-01 09:10 UTC, dariametelitsa approved these changes

2024-11-01 09:14 UTC, dariametelitsa approved these changes
![image](https://github.com/user-attachments/assets/97098d01-ab59-403e-84e1-2762abb5b242)
И в идеале под мобилку стили поправить (можно отдельной задачей)

PS Вот откуда кнопка удаления фото профиля взялась)

2024-11-01 15:27 UTC, dariametelitsa commented on src/features/auth/model/index.ts
> +export { default as AuthStore } from './authStore'
Это поправлю в своем ПР, т.к. были проблемы

2024-11-03 17:25 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
> +              disabled={!isValid || isSubmitting || (!isDirty && !dirty)}
Верно, я изначально назвала переменную photoChanged, после, по совету Влада, переименовала в dirty

2024-11-03 17:50 UTC, tanya-kostecki commented on src/features/profile/settings/generalInfo/api/profile.api.ts
> +  public uploadAvatar(file: File): Promise<any> {
Без проблем, забыла поменять

2024-11-05 15:41 UTC, merged