IN-181 / refactor zod errors and README file
Mechanics-cloud/OurProject pull request #88
Opened 2024-11-01 12:47 UTC by OchirovBair

refactor:

-  README file, 
-  refactor zod schemes in signIn, signUp, recovery password, forgot password forms

2024-11-01 13:11 UTC, jocker-py requested changes

2024-11-01 13:11 UTC, jocker-py commented on src/features/auth/model/forgotPassword/useForgotPassword.ts
> +  const { t } = useTranslation(() => trigger())
const { t } = useTranslation(trigger)

2024-11-01 13:11 UTC, jocker-py commented on src/features/auth/ui/signUp/SignUpForm.tsx
> -  const { t } = useTranslation()
лучше оставить как было, не мешать все в одно

2024-11-01 13:11 UTC, jocker-py commented on src/features/auth/model/signIn/singInSchema.ts
> +        /^(?=.*[0-9])(?=.*[A-Z])(?=.*[a-z])(?=.*[!"#$%&'()*+,\-./:;<=>?@[\]^_`{|}~])[0-9A-Za-z!"#$%&'()*+,\-./:;<=>?@[\]^_`{|}~]+$/,
регулярку перенеси в константы пожалуйста

2024-11-01 13:11 UTC, jocker-py commented on src/features/auth/model/signIn/singInSchema.ts
> +      .string({ required_error: t.signInForm.schemaErrors.emailRequiredError })
это не индивидуальная ошибка сугубо для signIn формы, а глобальная что может использоваться во всех компонентах. имеет смысл создать ключ validation и туда добавлять такого рода переводы иначе для каждой формы будут дублироваться проверки

2024-11-02 02:58 UTC, OchirovBair commented on src/features/auth/model/forgotPassword/useForgotPassword.ts
> +  const { t } = useTranslation(() => trigger())
TS2448: Block-scoped variable trigger used before its declaration.

Поэтому функция в функции

2024-11-02 03:01 UTC, OchirovBair commented on src/features/auth/ui/signUp/SignUpForm.tsx
> -  const { t } = useTranslation()
t нужна внутри useSignUp для того чтобы пробросить в signInSchema которая в useForm,  ну или как вариант оставить useTranslation снаружи useSignUp, но пробрасывать t как аргумент в useSignUp

2024-11-05 18:22 UTC, dariametelitsa commented on .env.example
А зачем переименовал в env.example?

2024-11-09 18:49 UTC, jocker-py approved these changes

2024-11-09 18:50 UTC, jocker-py approved these changes

2024-11-09 20:38 UTC, dariametelitsa approved these changes

2024-11-09 20:38 UTC, merged